### ISSUE TITLE
Strip unnecessary cookies

### ISSUE THREAD

**Issue by melithine** [whimsical-c4lic0/OF-DL-Auth-Helper#4]
We've been getting reports from a number of folks that have been using the extension with OF DL that they are getting intermittent 403 errors. Some people have indicated that trimming the `_cfuvid`/`__cf_bm` portions of the COOKIE values in specific resolve the errors. However, the only values needed are the `auth_id` and `sess`. It would be good if we could strip the other values so they don't cause problems. 

I haven't seen this issue myself, so I can't repro it, but I've seen a number of people mention this.

**Comment by whimsical-c4lic0** [comment]
I didn't encounter any problems in my testing, so I just published [v0.0.9](https://github.com/whimsical-c4lic0/OF-DL-Auth-Helper/releases/tag/v0.0.9) to strip the unnecessary cookies from the generated `auth.json` output. Thanks for creating the issue!
